### ISSUE TITLE
请问有对应的文章链接吗？

### ISSUE THREAD

**Issue by shwang1024** [zhaolin820/ris-aided-fual-functional-radar-and-communications-beamforming-design#2]
您好，请问有对应的文章链接吗？想要学习一下。

**Comment by zhaolin820** [comment]
您好，对应文章在[thesis](https://github.com/zhaolin820/ris-aided-dual-functional-radar-and-communications-beamforming-design/tree/main/thesis)文件夹下

**Comment by shwang1024** [comment]
> 您好，对应文章在[thesis](https://github.com/zhaolin820/ris-aided-dual-functional-radar-and-communications-beamforming-design/tree/main/thesis)文件夹下

**Comment by shwang1024** [comment]
十分感谢！
